name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-15 llvm-15

      - name: Setup LLVM tools
        run: |
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-15 1000
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-15 1000

      - name: Install xmake
        run: |
          curl -fsSL https://xmake.io/shget.text | bash
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Configure xmake
        run: |
          xmake config --toolchain=clang --mode=debug --yes

      - name: Build (Debug)
        run: |
          xmake build

      - name: Run tests (Debug)
        run: |
          xmake test

      - name: Configure xmake (Release)
        run: |
          xmake config --toolchain=clang --mode=release

      - name: Build (Release)
        run: |
          xmake build

      - name: Run tests (Release)
        run: |
          xmake test

  clang-format:
    name: Code Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-15

      - name: Check formatting
        run: |
          find . -name '*.cpp' -o -name '*.h' | grep -v build | grep -v googletest | grep -v _deps | xargs clang-format-15 --dry-run --Werror
